### PR TITLE
Adding support for JDK 11 and fixing integration test

### PR DESCRIPTION
**Pull request by nickwongdev**

### CODE REVIEW

**Comment by Stormcore** [comment]
looking forward this PR for oracle jdk and openjdk 11 support

**Comment by nwong-blz** [comment]
Could you guys at least merge this pull request in as of the three, it is the least impactful, works, and passes all tests?

**Comment by nickwongdev** [comment]
For everyone waiting on this pull request to be merged, I have started the process for hosting a fork of the project on Maven Central. Please add your support for this fork to be added to maven central here: 
https://issues.sonatype.org/browse/OSSRH-44691

Ignore the above failures, I'll fix the build issues caused by this automatically updated pull request so the checks will start passing again.

**Comment by nickwongdev** [comment]
Fork of project now synced. Searches will take a while longer to update, but should be up by EOB today.

Direct Download:
https://search.maven.org/remotecontent?filepath=com/nickwongdev/aspectj-maven-plugin/1.12.1/aspectj-maven-plugin-1.12.1.jar

Maven Dependency:
<dependency>
  <groupId>com.nickwongdev</groupId>
  <artifactId>aspectj-maven-plugin</artifactId>
  <version>1.12.1</version>
</dependency>

**Comment by missedone** [comment]
any update on the PR review and merge process? anybody maintains this project?

**Comment by alievmirza** [comment]
maybe @davidkarlsen might shed light on current status for that changes

**Comment by teenaBuchade** [comment]
Any updates on when support for JDK 11 will be available.

**Comment by akpai** [comment]
Any update on when this PR will be merged and support for jdk 11 will be available?

**Comment by sanyalpp** [comment]
Why is this PR not getting merged? We need this Open JDK 11 support guys!

**Comment by AkshayIyer12** [comment]
Any update on this?

**Comment by mariaoks** [comment]
any update? 
when can I use this for java 11?
<groupId>org.codehaus.mojo</groupId>
<artifactId>aspectj-maven-plugin</artifactId>
<version>1.11</version>

**Comment by vigneshse** [comment]
Execution default of goal org.codehaus.mojo:aspectj-maven-plugin:1.11:compile failed: Plugin org.codehaus.mojo:aspectj-maven-plugin:1.11 or one of its dependencies could not be resolved: Could not find artifact com.sun:tools:jar:11.0.3 at specified path /Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home/../lib/tools.jar -> 

Injection of the newer version solves the above issue.
<dependency>
  <groupId>com.nickwongdev</groupId>
  <artifactId>aspectj-maven-plugin</artifactId>
  <version>1.12.1</version>
</dependency>

Watching for the PR to be merged. 
Any update?

**Comment by Shanky2304** [comment]
Can we merge this now? I couldn't understand if there's another blocker here? This looks to be the issue blocking [version 1.11.1 release]( https://github.com/mojohaus/aspectj-maven-plugin/milestone/6).

**Comment by tranthanhdeveloper** [comment]
> **The package javax.xml.transform is accessible from more than one module: <unnamed>, java.xml
> [ERROR] error at import javax.xml.transform.Source;**

Anyone got this problem when compiling with JDK 11, I have add more module to using

```
		<dependency>
			<groupId>com.sun.xml.ws</groupId>
			<artifactId>jaxws-ri</artifactId>
			<version>2.3.2</version>
			<type>pom</type>
		</dependency>
```

**Comment by arnabcse28** [comment]
Are we planning to merge this anytime soon?

**Comment by TavernierCedric** [comment]
Any updates on when support for JDK 11 will be available.

**Comment by kriegaex** [comment]
Please, pretty please? We are on [AspectJ 1.9.5 and Java 13](https://www.eclipse.org/aspectj/doc/released/README-195.html) support already.

**Comment by kriegaex** [comment]
Thanks for moving this forward, but as I said, with AJ 1.9.5 we are at Java 13 language level already.

**Comment by esimioni** [comment]
@nickwongdev Thanks for providing a separate plugin that works with Java 11.
It solved half of my problems, it works great while use plain Maven, but it doesn't work with Eclipse + Maven + AJDT Configurator. I believe the problem is that AJDT Configurator doesn't recognize the plugin due to the different **groupId**.
As apparently nobody cares for this plugin anymore (more than a year without the PR), would you be so kind as to provide a distribution without changing the **groupId**?
Maybe the version could be used to differentiate from the "official", something like 1.12.1-java11 or 1.12.1-nickwongdev.

**Comment by kriegaex** [comment]
In order to upload a new artifact to Maven Central you ought to have access to the user account associated with a group ID. So it is not as simple as that.

**Comment by esimioni** [comment]
Thanks for the clarifications @nickwongdev. I ended up doing exactly what you said, and it worked with both plain Maven and Eclipse + AJDT.

For anyone going for this solution, the only obstacle I had was the need to explicitly force the plexus-utils plugin to 3.3.0, somehow it was picking up version 1.1, even though 3.3.0 is declared in the plugin POM.

For reference, this was the error before forcing plexus utils to 3.3.0:

`A required class was missing while executing org.codehaus.mojo:aspectj-maven-plugin:1.12.2-java11:compile: [Lorg/codehaus/plexus/util/Scanner;`

**Comment by kriegaex** [comment]
Sorry @nickwongdev, but just upgrading to AspectJ 1.9.5 won't extend the plugin to support source/target levels 12 and 13, maybe you ought to do that first before you cut a new release.

**Comment by nickwongdev** [comment]
> Sorry @nickwongdev, but just upgrading to AspectJ 1.9.5 won't extend the plugin to support source/target levels 12 and 13, maybe you ought to do that first before you cut a new release.

Thanks Kriegaex, I was fairly sure this would be an issue. Based on another pull request I have from Ghost, I am adding 12 and 13 to the compliance levels. However, I haven't tested any of this compliance. 

Ghost's pull request: https://github.com/nickwongdev/aspectj-maven-plugin/pull/1/files

**Comment by nickwongdev** [comment]
For everyone looking for JDK 12 and 13 compatibility, the SNAPSHOT is up in Sonatype and I have a ticket open to fix the automatic publishing of the released artifact. We jumped some versions while I was trying to get the gpg key and other things working properly. For now, maybe you can use the SNAPSHOT

<dependency>
  <groupId>com.nickwongdev</groupId>
  <artifactId>aspectj-maven-plugin</artifactId>
  <version>1.12.6-SNAPSHOT</version>
</dependency>

Or if you have an OSS account, download the snapshot JAR manually:
https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=com.nickwongdev&a=aspectj-maven-plugin&v=1.12.6-SNAPSHOT&e=jar

**Comment by nickwongdev** [comment]
OK, after some help from Sonatype, I figured out how to get the release pushed. You should now be able to use 

`<dependency>
  <groupId>com.nickwongdev</groupId>
  <artifactId>aspectj-maven-plugin</artifactId>
  <version>1.12.6</version>
</dependency>`

Sorry for the delay. My next goal is to get the integration tests working and passing in Travis so the PR is clean again.

**Comment by nickwongdev** [comment]
Also, FYI for anyone using my fork, IntelliJ has agreed to add Automatic Detection for the plugin in 2020.1  EAP. Also, there's a workaround to get Eclipse to do the same. So, it should function in the IDEs as if you are using the normal one. https://youtrack.jetbrains.com/issue/IDEA-230356

**Comment by jmatzen** [comment]
Thanks for looking into this @nickwongdev I'm knee deep in this stuff right now. ;)

**Comment by kriegaex** [comment]
Thank you so much, @nickwongdev . I have not tried yet, but one question:

> there's a workaround to get Eclipse to do the same

Can you describe the workaround or send post a link, please?

**Comment by kriegaex** [comment]
@nickwongdev, I want to discuss something in private with you Can you please reach out via contact form of my website or one of the contact methods listed on my StackOverflow profile page (scroll down the profile text)?

**Comment by nickwongdev** [comment]
> Thank you so much, @nickwongdev . I have not tried yet, but one question:
> 
> > there's a workaround to get Eclipse to do the same
> 
> Can you describe the workaround or post a link, please?

Unfortunately I can't find the thing I was referencing. I believe it was actually a maven fix and they just happened to be using Eclipse. :( 

> @nickwongdev, I want to discuss something in private with you. Can you please reach out via contact form of my website or one of the contact methods listed on my StackOverflow profile page (scroll down the profile text)?

done!

**Comment by nickwongdev** [comment]
Thanks for approving, it will continue to fail checks until we update the tests to run with JDK 11. :( Travis no longer allows JDK 8 based tests.

**Comment by pbeaume** [comment]
Any chance that something moves ?

**Comment by dheid** [comment]
Can I help with anything to move this forward?

**Comment by pankajagrawal16** [comment]
It will be great if we can have a official version that works with newer java versions.

**Comment by AjitDas** [comment]
can this feature be merged and released please please ? it's been a while since this critical feature is not implemented.

**Comment by pankajagrawal16** [comment]
Hi @nickwongdev, Anything I could help with to expedite this? Happy to help.:)

**Comment by softwarebrahma** [comment]
Can this be merged please?....is there something i can do to help?...we use this heavily & are unable to migrate to java 11 without this.

**Comment by softwarebrahma** [comment]
> Hi @nickwongdev, Anything I could help with to expedite this? Happy to help.:)

Hi @nickwongdev, Same here...is there anything I could help with here?

**Comment by mustaphazorgati** [comment]
Hey @nickwongdev!
I just saw this PR. We need JDK11 support too. I think one reason why this is not merged is because you have a lot of noise within your PR. Should we create a PR which just contains the necessary changes to get this done?

**Comment by kriegaex** [comment]
No, @mustaphazorgati, that is not the reason. It is much simpler: The Mojohaus plugin has not been actively maintained for quite a long time now (~3 years). @davidkarlsen is too busy with other things, as he told me, and Mojohaus never appointed @nickwongdev the maintainer. The story is a bit more complicated than this, but it is the short version for you.

**Comment by mustaphazorgati** [comment]
Hey @kriegaex,

thank you for your quick reply. So we have to wait and see what happens? Until then just use the fork from @nickwongdev? :P

**Comment by kriegaex** [comment]
Kind of, yes. I thought about taking care of the plugin myself, but I want to avoid having to comply to a lot of internal regulations at Mojohaus. I have never written a Maven plugin by myself either, so I am not an expert, rather an AspectJ buff. I would maybe provide PRs for the plugin in order to keep it up to the same level as AspectJ, but who should process them? At the end of the day I would create another fork.

**Comment by nickwongdev** [comment]
Unfortunately I can no longer contribute to any open source initiatives at
this time. So I suggest you fork what I have if you need additional
changes.

**Comment by kriegaex** [comment]
> Unfortunately I can no longer contribute to any open source initiatives at this time. So I suggest you fork what I have if you need additional changes.

Done: https://github.com/dev-aspectj/aspectj-maven-plugin. The read-me briefly explains
  * the project history and also
  * new features (Java 14-16, support for `--module-path`, `--enable-preview` compiler options).

See https://github.com/eclipse/org.aspectj/pull/41#issuecomment-826066012 if you want to use a snapshot from my Maven repository on `aspectj.dev` instead of building by yourself.

**Comment by olamy** [comment]
Thanks.  support to java 16 now in master.

**Comment by pankajagrawal16** [comment]
Are there plans to make an official release soon? @olamy @bmarwell

**Comment by bmarwell** [comment]
I'd love to do a release soon. Mid of June perhaps?
I am still browsing the other issues. Some of them are already resolved.

**Comment by kriegaex** [comment]
@pankajagrawal16, on Maven Central you find the [AspectJ.dev release 1.13.M3](https://mvnrepository.com/artifact/dev.aspectj/aspectj-maven-plugin/1.13.M3). As mentioned above, the source code is [here](https://github.com/dev-aspectj/aspectj-maven-plugin) and also the [plugin documentation](https://dev-aspectj.github.io/aspectj-maven-plugin/).

Just like the current snapshot of this repository, the AspectJ.dev version is based on [AspectJ 1.9.7.M3](https://mvnrepository.com/artifact/org.aspectj/aspectjrt/1.9.7.M3). I have been developing both the upcoming AspectJ version and the AspectJ Maven plugin in parallel, so they fit together. Of course, you can also wait for a release of this variant, if you prefer and if you don't trust an AspectJ committer.

Please be aware of the fact that both plugins can only depend on an AspectJ milestone in order to support Java 15/16, until there is a final release of AspectJ 1.9.7, which I cannot promise we shall release until mid June. Andy Clement and myself as current maintainers need to wait for some internal Eclipse reviews to be finished, before we can release a final version. But don't worry, you can use either of the two plugin variants and AspectJ 1.9.7.M3. The latter should be pretty stable, all tests are passing and we do not have plans to change major things until the release. OSS needs user feedback, so please support the guys here and the AspectJ team. 🙂

**Comment by bmarwell** [comment]
I can confirm that Alex' plugin is a good option for now. He did good work, and I might cherry pick some of his commits back (so the authorship does not get lost).
I was even thinking of adding his fork to the front page.

**Comment by kriegaex** [comment]
> I might cherry pick some of his commits back (so the authorship does not get lost)

@bmarwell, if you do, please let us talk first. The code base ist still pretty much the same, but not quite, and the build files and Javadocs also begin to diverge. Let us cooperate rather then hack away and let it diverge further. But please, let us avoid writing further offline messages. I prefer a chat tool like Telegram or Gitter. (You can use Gitter with your GitHub account.) Too much chaos has already arisen.

**Comment by bmarwell** [comment]
I definitely wouldn't mind! I will ask ASF Infra if we can use the ASF slack for mojohaus. If not, Gitter is probably the second-best option (looking for a #mojohaus channel).

**Comment by weaselmetal** [comment]
May I suggest that to haven an open issue for supporting Java 11 (or in general newer Java versions)?
I visited this repo a couple of times before finding this closed issue https://github.com/mojohaus/aspectj-maven-plugin/issues/41
Since there is something happening again, and Java 11 support may in fact come soon, should that ticket be reopened or another one be created?

**Comment by kriegaex** [comment]
Lately, I opened an AspectJ Slack because Andy has to use Slack at his daytime job anyway and knows it. Currently, it is just us two there. I could open a channel there, but am not sure if then you can also read all the AspectJ internal stuff. If there is a way to open a closed group, it would be an option. but I am just one person, you are multiple. So probably it is better if you open a channel somewhere comfortable for you guys.

How about some old-fashioned audio chat for a start? It makes people see others as people too, not as anonymous resources. It saves a ton of time, too.

**Comment by weaselmetal** [comment]
Is this the best ticket to follow if I want to stay informed when a new version of this plugin is available?
Should the ticket perhaps be reopened until a new version of the plugin has been released?
For anyone who hasn't been following this conversion already, it's hard to even figure out that this project has been revived and things are happening again.

**Comment by bmarwell** [comment]
> it's hard to even figure out that this project has been revived

I usually take a look at the last commits, when they happened and how frequently.

But yes, I am going to make a release soon, hopefully this month.

**Comment by mbesoft** [comment]
Looking forward to use it ^^

**Comment by jan-swiecki** [comment]
Yes, indeed, waiting for the update as well!

**Comment by olamy** [comment]
1.14.0 released

**Pull request closed without merging**
