### PR TITLE
Fix build to make runtime work on JDK 9/10

### PR DESCRIPTION
**Pull request by ctomc**
addresses #24

### CODE REVIEW

**Comment by ctomc** [comment]
@davidkarlsen This test is actually wrong/problematic. And problem is related to combination of auto-value annotation processor not working when running on ECJ compiler (part of aspectjtools).
On top of that, test is really wrong. as fact that it was ever properly working was bug in version maven compiler plugin that is used in it (2.3.2) that doesn't process annotations.

If you upgrade compiler plugin to latest, it will process annotation as part of maven compile process which will in the end result in error from aspectj compiler that class already exists.
but if you disable annotation processing in (newer) maven compiler and let aspectj compiler do it's work it will always fail with "@AutoValue processor threw an exception: java.lang.NullPointerException"
Which is I think a bug in either auto-value processor or ECJ.

Probably best if this test is disabled for time being.

**Comment by ctomc** [comment]
@davidkarlsen what should we do about this?

**Comment by davidkarlsen** [comment]
I can't remember why it was made - maybe git history can reveal the reason. I'd suggest replacing it with a better test.

**Comment by martinaldrin** [comment]
Hi, I wonder when we can expect to have Java 9 / Java 10 support?

**Comment by davidkarlsen** [comment]
@martinaldrin see thread above - there is a failing test which needs to be fixed

**Comment by ctomc** [comment]
@davidkarlsen I've updated the PR that now passes all tests on JDK8. I had to update config for all tests to enforce version of compiler plugin as well as set source/target version.

Project now compiles on JDK8/9/10.
But tests wont pass on JDK 9/10 as for that we would need to update aspectj dependency to 1.9.x
Once I do that, we get to test failures, 
- AnnotationProcessingOutput
- WrongCompilerVersion

Both are caused by aspectj itself so I have not upgraded it in plugin to 1.9.x as of now.

If you marge this and publish a release, users will be able to use on JDK 9/10,
but would need to manually override version of aspectj when using it (which is an fine workaround)

config should be something like that:
```xml
<plugin>
	<groupId>org.codehaus.mojo</groupId>
	<artifactId>aspectj-maven-plugin</artifactId>
	<version>${version.aspectj.plugin}</version>
	<executions>
	 ...
	</executions>
	<dependencies>
		<dependency>
			<groupId>org.aspectj</groupId>
			<artifactId>aspectjtools</artifactId>
			<version>1.9.1</version>
		</dependency>
	</dependencies>
	<configuration>
	 ....
	</configuration>
</plugin>
```

**Comment by martinaldrin** [comment]
How often do you do releases? can we expect that this will be released soon or how often do you do releases?

**Comment by infodroids** [comment]
Thanks, I am expecting this fix!

**Comment by nitinjadav** [comment]
Thanks, I am expecting this fix!

**Comment by martinaldrin** [comment]
Any updates on when this will be released?

**Comment by martinaldrin** [comment]
Hi, the code was merged 15 days ago, but I wonder when it will be released.

**Pull request merged**
