### PR TITLE
update aspectj to actual version 1.9.1

### PR DESCRIPTION
**Pull request by turbanoff**

### CODE REVIEW

**Comment by ehiggs** [comment]
I've rebased this locally and it still applies.

I've run the tests locally and I get the same error as Travis. This looks like a reprodution the following bugs that fail with a similar stack trace: 

https://bugs.eclipse.org/bugs/show_bug.cgi?id=535066


e.g.

```
ERROR] Failed to execute goal org.codehaus.mojo:aspectj-maven-plugin:1.11.1-SNAPSHOT:compile (default) on project annotation-processing-output: AJC compiler errors:
[ERROR] error at /Users/ehiggs/src/aspectj-maven-plugin/target/it/AnnotationProcessingOutput/src/main/java/Clazz.java:28::1244 @AutoValue processor threw an exception: java.lang.NullPointerException
[ERROR]     at org.aspectj.org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding.sourceStart(SourceTypeBinding.java:2472)
[ERROR]     at org.aspectj.org.eclipse.jdt.internal.compiler.lookup.MethodBinding.sourceStart(MethodBinding.java:1331)
[ERROR]     at org.aspectj.org.eclipse.jdt.internal.compiler.apt.model.TypeElementImpl$SourceLocationComparator.determineSourceStart(TypeElementImpl.java:98)
[ERROR]     at org.aspectj.org.eclipse.jdt.internal.compiler.apt.model.TypeElementImpl$SourceLocationComparator.getSourceStart(TypeElementImpl.java:71)
[ERROR]     at org.aspectj.org.eclipse.jdt.internal.compiler.apt.model.TypeElementImpl$SourceLocationComparator.compare(TypeElementImpl.java:64)
[ERROR]     at org.aspectj.org.eclipse.jdt.internal.compiler.apt.model.TypeElementImpl$SourceLocationComparator.compare(TypeElementImpl.java:1)
[ERROR]     at java.base/java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
[ERROR]     at java.base/java.util.TimSort.sort(TimSort.java:220)               
[ERROR]     at java.base/java.util.Arrays.sort(Arrays.java:1514)                
[ERROR]     at java.base/java.util.ArrayList.sort(ArrayList.java:1585)          
[ERROR]     at java.base/java.util.Collections.sort(Collections.java:176)       
[ERROR]     at org.aspectj.org.eclipse.jdt.internal.compiler.apt.model.TypeElementImpl.getEnclosedElements(TypeElementImpl.java:165)
...
```

There is also an error that resembles but it fails on a different line in SourceTypeBinding.sourceStart:

https://bugs.eclipse.org/bugs/show_bug.cgi?id=462782

```
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:aspectj-maven-plugin:1.11.1-SNAPSHOT:compile (default) on project annotation-processing-output: AJC compiler errors:
error at /Users/ehiggs/src/aspectj-maven-plugin/target/it/AnnotationProcessingOutput/src/main/java/Clazz.java:28::1244 @AutoValue processor threw an exception: java.lang.NullPointerException
    at org.aspectj.org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding.sourceStart(SourceTypeBinding.java:2472)
    at org.aspectj.org.eclipse.jdt.internal.compiler.lookup.MethodBinding.sourceStart(MethodBinding.java:1331)
    at org.aspectj.org.eclipse.jdt.internal.compiler.apt.model.TypeElementImpl$SourceLocationComparator.determineSourceStart(TypeElementImpl.java:98)
    at org.aspectj.org.eclipse.jdt.internal.compiler.apt.model.TypeElementImpl$SourceLocationComparator.getSourceStart(TypeElementImpl.java:71)
    at org.aspectj.org.eclipse.jdt.internal.compiler.apt.model.TypeElementImpl$SourceLocationComparator.compare(TypeElementImpl.java:64)
    at org.aspectj.org.eclipse.jdt.internal.compiler.apt.model.TypeElementImpl$SourceLocationComparator.compare(TypeElementImpl.java:1)
    at java.base/java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)   
    at java.base/java.util.TimSort.sort(TimSort.java:220)                       
    at java.base/java.util.Arrays.sort(Arrays.java:1514)                        
    at java.base/java.util.ArrayList.sort(ArrayList.java:1585)                  
    at java.base/java.util.Collections.sort(Collections.java:176)               
    at org.aspectj.org.eclipse.jdt.internal.compiler.apt.model.TypeElementImpl.getEnclosedElements(TypeElementImpl.java:165)
    at autovalue.shaded.com.google$.auto.common.$MoreElements.getLocalAndInheritedMethods($MoreElements.java:363)
```

If these are just sanity tests for the underlying aspectj that also has these errors, would it make sense to move forward with this patch so people can use aspectj with java 9, 10, 11, etc?

Thanks!

**Comment by andreas-schroeder** [comment]
Hi @davidkarlsen , any chances to get this merged and released? :)

**Comment by turbanoff** [comment]
@andreas-schroeder it's already done in master - https://github.com/mojohaus/aspectj-maven-plugin/commit/120ee1ce08b93873931035ed98cd70e3ccceeefb

**Comment by andreas-schroeder** [comment]
@turbanoff cool 👍, any plans on releasing it into the wild?

**Pull request closed without merging**
