### PR TITLE
Support Java 9-11

### PR DESCRIPTION
**Pull request by krinklesaurus**
Inspired from https://github.com/mojohaus/aspectj-maven-plugin/pull/50 and https://github.com/nickwongdev/aspectj-maven-plugin ❤️ 

Works locally for me. Not sure about the versioning though, let me know if you want to have another version.

### CODE REVIEW

**Comment by davidkarlsen** [comment]
Build seems to fail: https://travis-ci.org/github/mojohaus/aspectj-maven-plugin/builds/691775911

**Comment by krinklesaurus** [comment]
Looks like the maven cobertura plugin does not support Java 11. I set the distro to `trusty` cause then Java 8 is still supported.

**Comment by krinklesaurus** [comment]
@davidkarlsen ping

**Comment by krinklesaurus** [comment]
@davidkarlsen any chance this gets merged?

**Comment by krinklesaurus** [comment]
@davidkarlsen ping 😊

**Comment by mustaphazorgati** [comment]
@davidkarlsen ping. We'd love if this is merged.
CI seems to be good: https://travis-ci.org/github/mojohaus/aspectj-maven-plugin/builds/692147339

**Comment by olamy** [comment]
@krinklesaurus can you merge conflicts? Then it will be merged Thanks

**Comment by olamy** [comment]
thanks support up to java 16 now in master

**Pull request closed without merging**
