### PR TITLE
Specify output directories for annotation processing

### PR DESCRIPTION
**Pull request by nigelzor**
Without the -s argument, ajc will create files in the project root, which neither my IDE nor VCS appreciate.

I've matched the parameter names and default values used by maven-compiler-plugin, but maybe they should be something else? This does seem to work correctly when a build includes both plugins, and when using the aspectj plugin alone.

### CODE REVIEW

**Comment by nigelzor** [comment]
Rebased to pick up fixes to the Java 7 build. Is there anything blocking this from being merged?

**Comment by pasfilip** [comment]
Hi,
I'm in favor of including this change as well.
I have a workaround currently to have the sources generated by specifying  the option proc:only on the maven-compiler-plugin and set <proc>none</proc> in  the configuration element of the aspectj-maven-plugin.
Possibly nigelzor's change will work fine if the option proc:none is set on the  maven-compiler-plugin .

**Comment by davidkarlsen** [comment]
I cannot find any documentation for the "-s" option?
Also I think the dir should rather be ${project.build.directory}/generated-sources/aspectj-maven-plugin" to follow conventions

**Comment by pasfilip** [comment]
I believe it's the same flag as the standard javac options:
https://docs.oracle.com/javase/8/docs/technotes/tools/windows/javac.html

**Comment by hdave** [comment]
How should this "-s" be specified from within a Maven pom.xml?

**Comment by sp4ce** [comment]
@hdave did you figure it out?

**Comment by suryatej16** [comment]
Is there a plan to release a new version of the plugin with this fix?

**Pull request merged**
